spring:
  application:
    name: 04.sb-data-sorting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spg
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
